# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.5.1

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - echo "{\"jumpboxSshKey\":{\"value\":\"$JUMPBOX_SSH_KEY\"}}" > jumpboxParam.json
          - cat jumpboxParam.json
          - export "AZURE_PIPELINE_RG=PIPELINE_$$"
          - echo $AZURE_PIPELINE_RG
          - pipe: microsoft/azure-cli-run:1.0.1
            variables:
              AZURE_APP_ID: $AZURE_APP_ID
              AZURE_PASSWORD: $AZURE_PASSWORD
              AZURE_TENANT_ID: $AZURE_TENANT_ID
              CLI_COMMAND: 'az group create --resource-group $AZURE_PIPELINE_RG --location canadacentral'
              DEBUG: 'false'
          - pipe: microsoft/azure-cli-run:1.0.1
            variables:
              AZURE_APP_ID: $AZURE_APP_ID
              AZURE_PASSWORD: $AZURE_PASSWORD
              AZURE_TENANT_ID: $AZURE_TENANT_ID
              CLI_COMMAND: 'az group deployment create --resource-group $AZURE_PIPELINE_RG --template-uri https://bitbucket.org/atlassian/atlassian-azure-deployment/raw/master/jira/azuredeploy.json --parameters https://bitbucket.org/atlassian/atlassian-azure-deployment/raw/master/jira/azuredeploy.parameters.json --parameters @jumpboxParam.json'
              DEBUG: 'false'



