# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.5.6

options:
  max-time: 60
 
pipelines:
  custom:
    nightlySmokeTest:
    - step:
        caches:
          - pip
        script:
          - pip install --upgrade pip
          - pip install setuptools -U
          - pip install azure-cli
          - pip install jmespath
          - mkdir -p $BITBUCKET_CLONE_DIR/outputs
          - echo "BB_PIPELINE_$BITBUCKET_BUILD_NUMBER" > $BITBUCKET_CLONE_DIR/outputs/resourcegroup
          - export AZURE_PIPELINE_RG=$(cat $BITBUCKET_CLONE_DIR/outputs/resourcegroup)
          - env | sort
          - az login --service-principal --username $AZURE_APP_ID --password $AZURE_PASSWORD --tenant $AZURE_TENANT_ID
          - echo "{\"location\":{\"value\":\"$AZURE_LOCATION\"},\"jumpboxSshKey\":{\"value\":\"$JUMPBOX_SSH_KEY\"}}" > jumpboxParam.json
          - cat jumpboxParam.json
          - az group create --resource-group $AZURE_PIPELINE_RG --location $AZURE_LOCATION
          - az group deployment create --resource-group $AZURE_PIPELINE_RG --name $AZURE_PIPELINE_RG --template-uri https://bitbucket.org/atlassian/atlassian-azure-deployment/raw/master/jira/azuredeploy.json --parameters https://bitbucket.org/atlassian/atlassian-azure-deployment/raw/master/jira/azuredeploy.parameters.json --parameters @jumpboxParam.json | tee $BITBUCKET_CLONE_DIR/outputs/azureDeployOutput.json
          - cat $BITBUCKET_CLONE_DIR/outputs/azureDeployOutput.json
          - APP_ENDPOINT=$(jp.py -f $BITBUCKET_CLONE_DIR/outputs/azureDeployOutput.json 'properties.outputs.appEndpoint.value' | sed 's/"//g')
          - curl -sSf $APP_ENDPOINT/status
        artifacts:
          - outputs/**
        after-script:
          - az group delete --resource-group $(cat outputs/resourcegroup) --yes --no-wait

              



