# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.5.6

options:
  max-time: 60
 
pipelines:
  custom:
    nightlyJiraSmokeTest:
    - step:
        name: Build and deploy Jira
        caches:
          - pip
        script:
          - pip install --upgrade pip
          - pip install setuptools -U
          - pip install azure-cli
          - mkdir -p $BITBUCKET_CLONE_DIR/outputs
          
          # Have to use artifact file because env variables don't carry over to after-script
          - echo "BB_PIPELINE_$BITBUCKET_BUILD_NUMBER" > $BITBUCKET_CLONE_DIR/outputs/resourcegroup
          - export AZURE_PIPELINE_RG=$(cat $BITBUCKET_CLONE_DIR/outputs/resourcegroup)
          - az login --service-principal --username $AZURE_APP_ID --password $AZURE_PASSWORD --tenant $AZURE_TENANT_ID
          - echo "{\"location\":{\"value\":\"$AZURE_LOCATION\"},\"jumpboxSshKey\":{\"value\":\"$JUMPBOX_SSH_KEY\"}}" > jumpboxParam.json
          - cat jumpboxParam.json
          - az group create --resource-group $AZURE_PIPELINE_RG --location $AZURE_LOCATION
          
          # Have to use Azure pipe because azure cli fails eithout return error exit code. Sigh. 
          - pipe: microsoft/azure-arm-deploy:1.0.1 
            variables:
              AZURE_APP_ID: $AZURE_APP_ID
              AZURE_PASSWORD: $AZURE_PASSWORD
              AZURE_TENANT_ID: $AZURE_TENANT_ID
              AZURE_RESOURCE_GROUP: $AZURE_PIPELINE_RG
              AZURE_LOCATION: $AZURE_LOCATION
              AZURE_DEPLOYMENT_NAME: $AZURE_PIPELINE_RG
              AZURE_DEPLOYMENT_MODE: 'Complete'
              AZURE_DEPLOYMENT_TEMPLATE_URI: 'https://bitbucket.org/atlassian/atlassian-azure-deployment/raw/master/jira/azuredeploy.json'
              AZURE_DEPLOYMENT_PARAMETERS: 'https://bitbucket.org/atlassian/atlassian-azure-deployment/raw/master/jira/azuredeploy.parameters.json --parameters @jumpboxParam.json'
          
          # Got here so get deployment output. Can't get it from pipe as doesn't allow log capture/piping
          - az group deployment show --resource-group $AZURE_PIPELINE_RG --name $AZURE_PIPELINE_RG > $BITBUCKET_CLONE_DIR/outputs/azureDeployOutput.json
          
          # Get endpoint from Outputs section and ping heartbeat
          - APP_ENDPOINT=$(jp.py -f $BITBUCKET_CLONE_DIR/outputs/azureDeployOutput.json 'properties.outputs.appEndpoint.value' | sed 's/"//g')
          - echo "Testing app haertbeat at $APP_ENDPOINT/status"
          - curl -isSf --retry 5 --retry-connrefused $APP_ENDPOINT/status
        artifacts:
          - outputs/**
        after-script:
          - az group delete --resource-group $(cat outputs/resourcegroup) --yes --no-wait



    nightlyConfluenceSmokeTest:
    - step:
        name: Build and deploy Confluence
        caches:
          - pip
        script:
          - pip install --upgrade pip
          - pip install setuptools -U
          - pip install azure-cli
          - mkdir -p $BITBUCKET_CLONE_DIR/outputs

          # Have to use artifact file because env variables don't carry over to after-script
          - echo "BB_PIPELINE_$BITBUCKET_BUILD_NUMBER" > $BITBUCKET_CLONE_DIR/outputs/resourcegroup
          - export AZURE_PIPELINE_RG=$(cat $BITBUCKET_CLONE_DIR/outputs/resourcegroup)
          - az login --service-principal --username $AZURE_APP_ID --password $AZURE_PASSWORD --tenant $AZURE_TENANT_ID
          - echo "{\"location\":{\"value\":\"$AZURE_LOCATION\"},\"jumpboxSshKey\":{\"value\":\"$JUMPBOX_SSH_KEY\"}}" > jumpboxParam.json
          - cat jumpboxParam.json
          - az group create --resource-group $AZURE_PIPELINE_RG --location $AZURE_LOCATION

          # Have to use Azure pipe because azure cli fails eithout return error exit code. Sigh. 
          - pipe: microsoft/azure-arm-deploy:1.0.1 
            variables:
              AZURE_APP_ID: $AZURE_APP_ID
              AZURE_PASSWORD: $AZURE_PASSWORD
              AZURE_TENANT_ID: $AZURE_TENANT_ID
              AZURE_RESOURCE_GROUP: $AZURE_PIPELINE_RG
              AZURE_LOCATION: $AZURE_LOCATION
              AZURE_DEPLOYMENT_NAME: $AZURE_PIPELINE_RG
              AZURE_DEPLOYMENT_MODE: 'Complete'
              AZURE_DEPLOYMENT_TEMPLATE_URI: 'https://bitbucket.org/atlassian/atlassian-azure-deployment/raw/master/confluence/azuredeploy.json'
              AZURE_DEPLOYMENT_PARAMETERS: 'https://bitbucket.org/atlassian/atlassian-azure-deployment/raw/master/confluence/azuredeploy.parameters.json --parameters @jumpboxParam.json'
          
          # Got here so get deployment output. Can't get it from pipe as doesn't allow log capture/piping
          - az group deployment show --resource-group $AZURE_PIPELINE_RG --name $AZURE_PIPELINE_RG > $BITBUCKET_CLONE_DIR/outputs/azureDeployOutput.json

          # Get endpoint from Outputs section and ping heartbeat
          - APP_ENDPOINT=$(jp.py -f $BITBUCKET_CLONE_DIR/outputs/azureDeployOutput.json 'properties.outputs.appEndpoint.value' | sed 's/"//g')
          - echo "Testing app haertbeat at $APP_ENDPOINT/status"
          - curl -isSf --retry 5 --retry-connrefused $APP_ENDPOINT/status
        artifacts:
          - outputs/**
        after-script:
          - az group delete --resource-group $(cat outputs/resourcegroup) --yes --no-wait

              



